quarkus:
  application:
    name: factstore-server
  http:
    root-path: "/api"
  banner:
    path: factstore-banner.txt

factstore:
  storage:
    type: foundationdb
  foundationdb:
    cluster-file-path: /etc/foundationdb/fdb.cluster
    api-version: 730
